"""Generator for paper_a_supplementary.ipynb  (NeurIPS LMRL workshop — Paper A supp).

Supplementary figures S1-S9 + two methods panels, from the same local aggregates as the main
figures. Publication style; saved to figs_paper_a/ as .pdf + .png with an `s` prefix.

Run:  python _build_paper_a_supplementary.py   (then execute the notebook)

  S1   per-amino-acid identity heatmaps (AA × depth) — calibration detail behind Fig 1
  S2   diffusion layer × sampling-step probe-raw heatmaps (the full 2D grid behind Fig 3B)
  S4   in-sample (SAE-1feat) vs held-out (probe-raw) overshoot diagnostic — defends headline F1
  S5   SAE faithfulness: probe-SAE vs probe-raw (trunk ~98%, diffusion ~82% of the ceiling)
  S6   stability -> interpretability enrichment (Hungarian shared features, Fisher)  [R6, Paper B seed]
  S7   self-consistency: DSSP on Boltz-own vs AlphaFold structure
  S9   diffusion amino-acid identity — layer × recycle-step grids (probe / SAE / neuron / decoder-cos)
  SM1  why demean: activation energy concentration before/after mean removal
  SM2  decoder-direction collapse: ~5x duplicate directions; naive vs deduped cross-seed baseline
  SM3  the dedup correction to the cross-seed baseline
"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []
def md(s): cells.append(nbf.v4.new_markdown_cell(s))
def code(s): cells.append(nbf.v4.new_code_cell(s))

# ----------------------------------------------------------------- intro
md(r"""# Paper A — supplementary figures (NeurIPS LMRL workshop)

Generated by `_build_paper_a_supplementary.py` (edit the generator, not the .ipynb). Companion to
`paper_a_figures.ipynb`; reuses the identical loaders. Figures saved to `figs_paper_a/` with an `s`
prefix.

| fig | supports | content |
|---|---|---|
| S1 | R1 / Fig 1 | per-amino-acid identity F1, AA × depth — probe / **SAE / neuron** |
| S2 | R3 / Fig 3 | diffusion layer × step probe-raw grid (all concepts) |
| S4 | R3–R4 | in-sample SAE-1feat vs held-out probe-raw overshoot (rare concepts) |
| S5 | R4 | SAE faithfulness — probe on SAE latents vs raw activations |
| S6 | R6 | stability → interpretability — **AA + SS + SwissProt concept winners on one Hungarian footing** |
| S7 | R5 / Fig 5 | self-consistency: DSSP on Boltz-own vs AlphaFold structure |
| S9 | R1 / Fig 3 | diffusion amino-acid identity — layer × recycle-step grids (probe / SAE / neuron / decoder-cos) |
| S11 | R3 / Fig 3 | depth-matched trunk→diffusion drop with bootstrap CIs — geometry retained, chemistry collapses (✓ non-overlap) |
| SM1 | methods | activation-energy concentration → why we remove the mean |
| SM2 | methods | decoder-direction collapse (~5×) |
| SM3 | methods | the dedup correction to the cross-seed baseline |""")

# ----------------------------------------------------------------- setup (shared with main)
code(r"""import json, glob
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams.update({
    "figure.dpi": 120, "savefig.dpi": 300, "savefig.bbox": "tight", "figure.facecolor": "white",
    "font.size": 12, "axes.titlesize": 12, "axes.labelsize": 12,
    "legend.fontsize": 9, "xtick.labelsize": 10, "ytick.labelsize": 10,
    "axes.grid": True, "grid.alpha": 0.25, "axes.spines.top": False, "axes.spines.right": False,
    "pdf.fonttype": 42, "ps.fonttype": 42,
})

ROOT = Path.cwd()
DATA = ROOT / "data"   # committed summary data (agg JSONs + CSVs)
PF_DIRS  = {1: DATA/"sae_explore/layer_sweep_rec1/benchmark"}
DIFF_DIR = DATA/"sae_explore/diffusion_analysis"
FIG_DIR  = ROOT/"figures"; FIG_DIR.mkdir(parents=True, exist_ok=True)
MODULE_MAX = {"pairformer": 47, "diffusion": 22}
PF_REC, DIFF_REC = 1, 199
C_PF, C_DIFF = "#1f77b4", "#d62728"
C_PROBE, C_SAE, C_NEUR = "#2ca02c", "#1f77b4", "#ff7f0e"
SS = ["secondary_structure:helix", "secondary_structure:strand", "secondary_structure:coil"]
STRUCT_DUP = {"helix", "beta_strand", "turn", "coiled_coil"}

def short(c):
    return (c.replace("secondary_structure:", "ss:").replace("compositional_bias:", "cb:")
             .replace("modified_residue:", "mod:").replace("region:", "")
             .replace("glycosylation:n-linked_glcnac_asparagine", "glyc:n-linked"))

def save(fig, name):
    for ext in ("pdf", "png"): fig.savefig(FIG_DIR/f"{name}.{ext}")
    print("saved", (FIG_DIR/f"{name}.png").relative_to(ROOT), "(+ .pdf)")

def _flatten_agg(path, stack):
    d = json.load(open(path)); rec, layer, cset = d["rec"], d["layer"], d["concept_set"]
    return [dict(stack=stack, rec=rec, layer=layer, concept_set=cset, concept=concept,
                 sae_f1=c.get("sae_f1_mean"), sae_null=c.get("sae_null_mean"),
                 sae_sig=c.get("sae_sig_mean"), neuron_f1=c.get("neuron_f1"),
                 probe_raw_f1=c.get("probe_raw_f1"), probe_sae_f1=c.get("probe_sae_f1_mean"))
            for concept, c in d["per_concept"].items()]

def load_concepts():
    rows = []
    for rec, bench in PF_DIRS.items():
        for p in glob.glob(str(bench/"layer*/[sw]*_agg.json")): rows += _flatten_agg(p, "pairformer")
    for p in glob.glob(str(DIFF_DIR/"rec*/benchmark/layer*/[sw]*_agg.json")): rows += _flatten_agg(p, "diffusion")
    return pd.DataFrame(rows).drop_duplicates(["stack", "rec", "layer", "concept_set", "concept"])

df = load_concepts()
df["frac_depth"] = df["layer"] / df["stack"].map(MODULE_MAX)
df["probe_above_null"] = df["probe_raw_f1"] - df["sae_null"]
_by = df.groupby(["concept", "stack"])["probe_above_null"].median().unstack("stack")
INFO_CONCEPTS = sorted(_by.index[_by.max(axis=1) > 0.05])

def end_of_module(stack, rec):
    s = df[(df["stack"] == stack) & (df.rec == rec)]
    return s[s.layer == s.layer.max()].set_index("concept")

print("df rows:", len(df), "| informative concepts:", len(INFO_CONCEPTS))""")

# ================================================================= S1
md(r"""## S1 — Per-amino-acid identity (calibration detail behind Fig 1)

Fig 1 averaged over the 20 amino acids. Here is the full breakdown in the pairformer trunk across the
three readouts: the **probe is ~1.0 for every residue at every depth** (left — confirms
label/activation alignment for all AAs, not just on average); the **best single SAE latent** (middle)
recovers most residues cleanly and sharpens with depth; the **best single neuron** (right) is markedly
weaker and patchier — direct evidence that the sparse dictionary carves residue identity into cleaner
single features than the raw neuron basis does.""")

code(r"""aa = pd.DataFrame([json.loads(l) for l in
                   (DATA/"sae_explore/amino_acid_sanity/results.jsonl").read_text().splitlines() if l.strip()])
pf = aa[aa.layer_type == "pairformer"]
aa_order = sorted(pf.amino_acid.unique())
panels = [("probe_f1", "probe (full vector) — ~1.0"),
          ("sae_f1", "best single SAE latent"),
          ("neuron_f1", "best single neuron")]
fig, axes = plt.subplots(1, 3, figsize=(16, 5.2))
for ax, (col, title) in zip(axes, panels):
    piv = pf.pivot_table(index="amino_acid", columns="layer", values=col).reindex(aa_order)
    im = ax.imshow(piv.values, aspect="auto", cmap="viridis", vmin=0, vmax=1)
    ax.set_xticks(range(len(piv.columns)))
    ax.set_xticklabels([f"{c/MODULE_MAX['pairformer']:.2f}" for c in piv.columns], fontsize=7, rotation=90)
    ax.set_yticks(range(len(aa_order))); ax.set_yticklabels(aa_order if ax is axes[0] else [], fontsize=8)
    ax.set_xlabel("fractional depth"); ax.set_title(title); ax.grid(False)
axes[0].set_ylabel("amino acid")
fig.colorbar(im, ax=axes, fraction=0.018, pad=0.02, label="per-residue F1")
fig.suptitle("S1 · Amino-acid identity per residue (pairformer trunk) — probe / SAE / neuron", y=1.02)
save(fig, "s1_aa_per_residue"); plt.show()
print("mean over AA at trunk output (L47):")
print(pf[pf.layer == 47][["probe_f1", "sae_f1", "neuron_f1"]].mean().round(3))
print("diffusion coverage in AA file:", sorted(aa[aa.layer_type=='diffusion'].layer.unique()),
      "(L22 output only; the trunk->diffusion drop is in main Fig 3A)")""")

# ================================================================= S2
md(r"""## S2 — Diffusion layer × sampling-step grid (behind Fig 3B)

Fig 3B fixed the layer (L22) and swept sampling step. The diffusion representation actually lives on
**two** axes — depth (layer 0→22) and denoising time (step 0→199). Here is the full `probe-raw` grid
per concept (only computed cells shown; no interpolation). Geometry is bright across the whole grid
from the first step; chemistry (disulfide, signal peptide) is dark everywhere.""")

code(r"""concepts_show = ["secondary_structure:helix", "secondary_structure:coil",
                 "region:disordered", "signal_peptide", "disulfide_bond"]
steps_d  = [0, 10, 50, 100, 199]
layers_d = [0, 2, 4, 6, 10, 14, 18, 22]
fig, axes = plt.subplots(1, len(concepts_show), figsize=(3.5*len(concepts_show), 3.8))
im = None
for ax, concept in zip(axes, concepts_show):
    s = df[(df["stack"] == "diffusion") & (df.concept == concept)]
    piv = s.pivot_table(index="rec", columns="layer", values="probe_raw_f1").reindex(index=steps_d, columns=layers_d)
    im = ax.imshow(piv.values, aspect="auto", cmap="viridis", vmin=0, vmax=1, origin="lower")
    ax.set_xticks(range(len(layers_d))); ax.set_xticklabels(layers_d, fontsize=8)
    ax.set_yticks(range(len(steps_d)));  ax.set_yticklabels(steps_d, fontsize=8)
    ax.set_xlabel("diffusion layer (depth →)"); ax.set_title(short(concept), fontsize=10); ax.grid(False)
axes[0].set_ylabel("diffusion step (time ↑)")
fig.colorbar(im, ax=axes, fraction=0.012, pad=0.02, label="probe-raw F1")
fig.suptitle("S2 · Diffusion module: concept decodability over layer × sampling step", y=1.05)
save(fig, "s2_diffusion_layer_step"); plt.show()""")

# ================================================================= S4
md(r"""## S4 — In-sample vs held-out: the SAE-1feat overshoot (defends the headline F1)

`SAE-1feat` picks the best of 2048 latents × thresholds **in-sample**; `probe-raw` is **held-out**
(grouped K-fold by protein). So a single latent can "beat" the probe on a **rare** concept by
fitting those exact residues — a winner's-curse statistic, *not* evidence the SAE out-decodes
supervised learning. Left: every (layer, rec, concept) point, pairformer; the overshoot lives at
**low probe-raw** (rare concepts). Right: it concentrates on the rare/hard concepts. This is why we
lead with probe-raw for "can the module decode X".""")

code(r"""inv = df[df["stack"] == "pairformer"].dropna(subset=["sae_f1", "probe_raw_f1"]).copy()
inv["over"] = inv.sae_f1 > inv.probe_raw_f1
frac = inv.over.mean()
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
ax = axes[0]
for flag, c, lab in [(False, "#999999", "probe-raw ≥ SAE-1feat"), (True, C_DIFF, "SAE-1feat > probe-raw")]:
    g = inv[inv.over == flag]
    ax.scatter(g.probe_raw_f1, g.sae_f1, s=16, c=c, alpha=0.55, label=lab)
ax.plot([0, 1], [0, 1], "k:", lw=1); ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.set_aspect("equal")
ax.set_xlabel("probe-raw F1 (held-out)"); ax.set_ylabel("SAE-1feat F1 (in-sample)")
ax.set_title(f"SAE > probe in {frac*100:.0f}% of points"); ax.legend(fontsize=8, loc="lower right")
ax = axes[1]
gc = inv.groupby("concept").over.mean().sort_values()
ax.barh(range(len(gc)), gc.values, color=[C_DIFF if v > 0.5 else "#999999" for v in gc.values])
ax.set_yticks(range(len(gc))); ax.set_yticklabels([short(c) for c in gc.index], fontsize=7)
ax.set_xlabel("fraction of (layer,rec) points where SAE-1feat > probe-raw")
ax.set_title("overshoot concentrates on rare / hard concepts")
fig.suptitle("S4 · In-sample SAE-1feat vs held-out probe-raw", y=1.02)
save(fig, "s4_insample_vs_heldout"); plt.show()
print("mean F1 by group (overshoot = low probe-raw = rare):")
print(inv.groupby("over")[["sae_f1", "probe_raw_f1", "sae_null"]].mean().round(3))""")

# ================================================================= S5
md(r"""## S5 — SAE faithfulness (behind R4's diffusion caveat)

Does the sparse dictionary **preserve** concept information? Compare two held-out probes per concept:
on raw activations (`probe-raw`, the ceiling) vs on SAE latents (`probe-SAE`). Points on the diagonal
= the SAE kept the signal. The pairformer SAE retains **~98%** of the raw-probe ceiling; the diffusion
SAE only **~82%** — so single-feature F1 understates diffusion specifically, and is part of why we
lean on probe-raw for the cross-module claim.""")

code(r"""idf = df[df.concept.isin(INFO_CONCEPTS)]
idx = idf.groupby(["stack", "concept"]).probe_raw_f1.idxmax().dropna()
paired = df.loc[idx, ["stack", "concept", "probe_raw_f1", "probe_sae_f1", "sae_f1"]]
fig, axes = plt.subplots(1, 2, figsize=(13, 5.2), sharex=True, sharey=True)
for ax, stack, col in [(axes[0], "pairformer", C_PF), (axes[1], "diffusion", C_DIFF)]:
    p = paired[paired["stack"] == stack]
    ax.scatter(p.probe_raw_f1, p.probe_sae_f1, s=60, color=col, edgecolor="k", linewidth=0.4,
               alpha=0.85, label="probe-SAE (held-out)")
    ax.scatter(p.probe_raw_f1, p.sae_f1, s=28, color="grey", alpha=0.5, marker="x", label="SAE-1feat (in-sample)")
    ax.plot([0, 1], [0, 1], "k:", lw=1); ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.set_aspect("equal")
    ax.set_title(stack); ax.set_xlabel("probe-raw F1 (held-out ceiling)"); ax.legend(fontsize=8, loc="upper left")
axes[0].set_ylabel("probe-SAE F1 (dots) / SAE-1feat F1 (×)")
fig.suptitle("S5 · SAE faithfulness — does the dictionary keep the signal?", y=1.01)
save(fig, "s5_sae_faithfulness"); plt.show()
paired = paired.assign(retained=paired.probe_sae_f1 / paired.probe_raw_f1.where(paired.probe_raw_f1 > 0))
print("median probe-SAE / probe-raw (info retained):"); print(paired.groupby("stack").retained.median().round(3))""")

# ================================================================= S7
md(r"""## S7 — Self-consistency: DSSP on Boltz's own structure vs AlphaFold (complements Fig 5)

A second label-source check, complementary to the under-annotation result in Fig 5. Re-score the dense
DSSP secondary structure against Boltz's **own** predicted structure (`boltz_secondary`, produced in the
same forward pass — exact alignment, causally downstream of the representation) vs AlphaFold's structure
(`secondary`, third-party). The model's **own helices are ~0.06–0.08 F1 more decodable** at every depth
in both stacks (self-consistency signature); coil (the residual grab-bag class) goes the other way, so
report the per-class split, not the net mean.""")

code(r"""from aggregate_seed_benchmark import _aggregate_concept

def _ss_rows(layer_dir, set_name, stack, seeds=(1, 2, 3)):
    per = [json.load(open(p)) for s in seeds
           for p in [Path(layer_dir)/f"{set_name}_seed{s}_benchmark.json"] if p.exists()]
    if not per: return []
    base = per[0]
    return [dict(stack=stack, rec=base["rec"], layer=base["layer"], concept_set=set_name, concept=c,
                 probe_raw_f1=_aggregate_concept(base["layer"], c,
                     [e["per_concept"][c] for e in per if c in e["per_concept"]])["probe_raw_f1"])
            for c in sorted({c for e in per for c in e["per_concept"]})]

rows = []
for bench in PF_DIRS.values():
    for ld in glob.glob(str(bench/"layer*")):
        for s in ("secondary", "boltz_secondary"): rows += _ss_rows(ld, s, "pairformer")
for ld in glob.glob(str(DIFF_DIR/"rec*/benchmark/layer*")):
    for s in ("secondary", "boltz_secondary"): rows += _ss_rows(ld, s, "diffusion")
ssw = (pd.DataFrame(rows).pivot_table(index=["stack", "rec", "layer", "concept"],
       columns="concept_set", values="probe_raw_f1").dropna().reset_index())

fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.4), sharey=True)
for ax, (stack, rec) in zip(axes, [("pairformer", PF_REC), ("diffusion", DIFF_REC)]):
    s = ssw[(ssw["stack"] == stack) & (ssw["rec"] == rec)]
    x = np.arange(len(SS)); w = 0.38
    for k, (src, col, hatch, lab) in enumerate([
            ("secondary", "#7f7f7f", None, "AlphaFold (3rd-party)"),
            ("boltz_secondary", (C_PF if stack == "pairformer" else C_DIFF), "//", "Boltz-own (self-consistent)")]):
        m = [s[s.concept == c][src].mean() for c in SS]
        sd = [s[s.concept == c][src].std() for c in SS]
        ax.bar(x + (k - 0.5)*w, m, w, yerr=sd, capsize=3, color=col, hatch=hatch,
               edgecolor="k", linewidth=0.4, label=lab)
    ax.set_xticks(x); ax.set_xticklabels([c.split(":")[1] for c in SS])
    ax.set_title(f"{stack}  (mean ± sd over {s.layer.nunique()} layers)"); ax.set_ylim(0, 1)
axes[0].set_ylabel("probe-raw F1  (held-out)"); axes[0].legend(loc="lower left", framealpha=0.9)
fig.suptitle("SS decodability by label SOURCE — the model's own helices decode better", y=1.02)
save(fig, "s7_ss_self_consistency"); plt.show()
d = ssw.assign(delta=ssw.boltz_secondary - ssw.secondary).groupby("concept")["delta"].mean().round(3)
print("mean ΔF1 (Boltz-own − AlphaFold) by SS class:"); print(d.to_string())""")

# ================================================================= S9
md(r"""## S9 — Diffusion amino-acid identity: layer × recycle-step grids

The pairformer trunk encodes amino-acid identity cleanly (S1). Once activations enter the diffusion
module the picture changes: the **linear probe** still recovers identity at ~0.65–0.91 F1 (sequence
information is present), but the **best single SAE latent** collapses to ~0.20–0.44 — far below the
neuron (0.44–0.50) — meaning the diffusion dictionary does **not** concentrate residue identity into
monosemantic features the way the trunk does. Cross-seed **decoder cosine** is also lower, consistent
with the SAE latents being less reproducible on this chemical concept.

The four panels are the same `layer × recycle-step` grids as in the amino-acid identity notebook
(section 7), computed from `amino_acid_cross_seed.py --layer_type diffusion`.""")

code(r"""AA_DIR = DATA/"sae_explore/amino_acid_sanity"

def _load_jsonl(path):
    p = Path(path)
    if not p.exists(): return pd.DataFrame()
    return pd.DataFrame([json.loads(l) for l in p.read_text().splitlines() if l.strip()])

xs_diff = _load_jsonl(AA_DIR/"cross_seed_results_diffusion.jsonl")
if xs_diff.empty or not (xs_diff.get("layer_type", pd.Series(dtype=str)) == "diffusion").any():
    print("No diffusion cross-seed AA rows — run amino_acid_cross_seed.py --layer_type diffusion first.")
else:
    d = xs_diff[xs_diff.layer_type == "diffusion"].copy()
    agg = d.groupby(["rec", "layer"]).agg(
        sae=("sae_f1_mean", "mean"), neuron=("neuron_f1", "mean"),
        probe=("probe_f1", "mean"), decoder_cos=("decoder_cos_mean", "mean")).reset_index()
    recs   = sorted(d.rec.unique())
    layers = sorted(d.layer.unique())

    def _grid(col):
        m = np.full((len(recs), len(layers)), np.nan)
        for _, r in agg.iterrows():
            m[recs.index(r["rec"]), layers.index(r["layer"])] = r[col]
        return m

    PANELS = [("sae", "best SAE latent F1"), ("neuron", "best neuron F1"),
              ("probe", "linear probe F1"), ("decoder_cos", "cross-seed decoder cosine")]
    fig, axes = plt.subplots(1, 4, figsize=(16, 3.4))
    im = None
    for ax, (col, title) in zip(axes, PANELS):
        m = _grid(col)
        im = ax.imshow(m, cmap="viridis", vmin=0, vmax=1, aspect="auto")
        ax.set_xticks(range(len(layers))); ax.set_xticklabels(layers, fontsize=9)
        ax.set_yticks(range(len(recs)));  ax.set_yticklabels(recs, fontsize=9)
        ax.set_xlabel("diffusion layer"); ax.set_ylabel("recycle step" if ax is axes[0] else "")
        ax.set_title(title, fontsize=10); ax.grid(False)
        for i in range(len(recs)):
            for j in range(len(layers)):
                if np.isfinite(m[i, j]):
                    ax.text(j, i, f"{m[i,j]:.2f}", ha="center", va="center",
                            color="w" if m[i, j] < 0.6 else "k", fontsize=8)
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
    fig.suptitle(
        "S9 · Diffusion module: amino-acid identity (mean over 20 AAs)\n"
        "probe still sees sequence; SAE latents do not concentrate it into monosemantic features",
        y=1.06)
    save(fig, "s9_diffusion_aa_grid"); plt.show()
    print("Summary (mean over AAs and layers):")
    print(agg[["rec", "layer", "sae", "neuron", "probe", "decoder_cos"]].round(3).to_string(index=False))""")

# ================================================================= S11
md(r"""## S11 — Depth-matched trunk→diffusion drop, with bootstrap CIs (does the gap survive uncertainty?)

The headline claim is a *comparison*: geometry
is retained into the diffusion module, sequence-chemistry is discarded. Here we put both stacks'
**depth-matched module outputs** (pairformer L47 = trunk output, diffusion L22 = module output) on one
axis with their 95% by-protein bootstrap CIs, so the gap can be read against its own uncertainty. A ✓
marks concepts whose trunk CI lies **entirely above** the diffusion CI — a deliberately conservative
test (non-overlap of two independent 95% intervals corresponds to roughly p < 0.006).

* **Geometry (top).** Dense DSSP secondary structure decodes at ~0.82–0.90 in **both** stacks with
  tightly overlapping CIs — diffusion keeps it essentially unchanged. (`region:disordered` drops modestly,
  0.87→0.70, but stays high: retained, not discarded.)
* **Chemistry (bottom).** The diffusion estimate collapses toward the floor. For the well-powered drops
  (signal_peptide, disulfide_bond, low-complexity) the CIs are **non-overlapping** even at small n; the
  rarest labels (glycosylation 47, cb:polar 19) show the same large gap but their wide intervals overlap —
  we do **not** claim per-concept significance there, which is the honest read of a 99-protein set.

Geometry uses the dense DSSP set (`secondary`, 393 proteins — hence the very tight CIs and large domain
counts); chemistry uses the 99-protein SwissProt set, matching the family split in main Fig 3A. A fully
paired bootstrap on the per-concept gap (resampling proteins jointly) would tighten the rare-label tests
further and is the natural next step if per-concept significance is needed for those labels.""")

code(r"""ci = pd.read_csv(DATA/"sae_explore/concept_f1_ci.csv")
prc = ci[ci.method == "probe_raw"]
# geometry exemplars = dense DSSP SS + disordered; chemistry = SwissProt functional (sparse SS dups excluded)
GEOM = [("secondary", "secondary_structure:coil"), ("secondary", "secondary_structure:helix"),
        ("secondary", "secondary_structure:strand"), ("swissprot", "region:disordered")]
CHEM = [("swissprot", c) for c in ["signal_peptide", "compositional_bias:basic_and_acidic_residues",
        "disulfide_bond", "compositional_bias:low_complexity", "compositional_bias:polar_residues",
        "glycosylation:n-linked_glcnac_asparagine", "binding_site:substrate", "modified_residue:phosphoserine"]]

def _row(cs, c, stack, layer):
    r = prc[(prc.concept_set == cs) & (prc.concept == c) & (prc["stack"] == stack) & (prc.layer == layer)]
    return r.iloc[0] if len(r) else None

def _pairs(pairs):
    out = []
    for cs, c in pairs:
        t, d = _row(cs, c, "pairformer", 47), _row(cs, c, "diffusion", 22)
        if t is None or d is None:
            continue
        out.append(dict(c=c, n=int(t.pos_domains), t=t.f1, tlo=t.f1_lo, thi=t.f1_hi,
                        d=d.f1, dlo=d.f1_lo, dhi=d.f1_hi, nonov=bool(t.f1_lo > d.f1_hi)))
    return sorted(out, key=lambda r: r["t"])

from matplotlib.lines import Line2D
ch, g = _pairs(CHEM), _pairs(GEOM)
ordered = ch + [None] + g                                   # chemistry block, divider, geometry block
y = np.arange(len(ordered))
fig, ax = plt.subplots(figsize=(8.8, 6.8))
for yi, r in zip(y, ordered):
    if r is None:
        continue
    ax.plot([r["d"], r["t"]], [yi, yi], color="#ccc", lw=2.2, zorder=1)
    ax.plot([r["tlo"], r["thi"]], [yi, yi], color=C_PF, lw=1.5, zorder=2)
    ax.plot([r["dlo"], r["dhi"]], [yi, yi], color=C_DIFF, lw=1.5, zorder=2)
    ax.scatter([r["t"]], [yi], color=C_PF, s=58, zorder=3, ec="k", lw=0.4)
    ax.scatter([r["d"]], [yi], color=C_DIFF, s=58, zorder=3, ec="k", lw=0.4)
    if r["nonov"]:
        ax.annotate("✓", (max(r["thi"], r["dhi"]) + 0.015, yi), va="center", fontsize=12, color="#2ca02c")
ax.set_yticks(y)
ax.set_yticklabels([f"{short(r['c'])}  (n={r['n']})" if r else "" for r in ordered], fontsize=9)
sep = len(ch)
ax.axhline(sep, color="k", lw=0.8, ls="--")
ax.text(0.01, sep - 0.5, "chemistry (sequence)", fontsize=9, color=C_DIFF, va="top", alpha=0.85)
ax.text(0.01, sep + 0.5, "geometry (structure)", fontsize=9, color=C_PF, va="bottom", alpha=0.85)
ax.set_xlim(0, 1.0); ax.set_ylim(-0.6, len(ordered) - 0.4)
ax.set_xlabel("probe-raw F1  (depth-matched: trunk L47 vs diffusion L22; 95% by-protein bootstrap CI)")
ax.legend(handles=[
    Line2D([0], [0], marker="o", color="w", mfc=C_PF, mec="k", ms=8, label="pairformer trunk (L47)"),
    Line2D([0], [0], marker="o", color="w", mfc=C_DIFF, mec="k", ms=8, label="diffusion (L22)"),
    Line2D([0], [0], marker=r"$\checkmark$", color="#2ca02c", ms=11, ls="none", label="CIs non-overlapping")],
    loc="lower right", fontsize=8.5)
ax.set_title("S11 · Geometry retained, chemistry discarded — depth-matched, with 95% CIs")
save(fig, "s11_trunk_vs_diffusion_ci"); plt.show()
print("depth-matched trunk(L47) vs diffusion(L22), non-overlap = trunk CI entirely above diffusion CI:")
for r in ch + g:
    print(f"  {r['c']:45s} n={r['n']:5d}  trunk {r['t']:.2f}  diff {r['d']:.2f}  gap {r['t']-r['d']:+.2f}  nonoverlap={r['nonov']}")""")

nb["cells"] = cells
nb["metadata"] = {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                  "language_info": {"name": "python"}}
out = "paper_a_supplementary.ipynb"
nbf.write(nb, out)
print("wrote", out, "with", len(cells), "cells")
